### ISSUE TITLE
Cannot create new recipes without a photo

### ISSUE THREAD

**Issue by clettenberg** [boblail/recipes#1]
Recipes cannot be created without attaching a photo. [This method](http://github.com/boblail/recipes/blob/97a0cf9e1b746159398ba7cbd798793992f565d5/app/models/photo.rb#L13) never runs because calling `Recipe.new` does not instantiate a new photo as well. When you go to save you get this error.

```sql
PG::InvalidTextRepresentation: ERROR:  invalid input syntax for uuid: ""
: SELECT  "photos".* FROM "photos"  WHERE "photos"."id" = $1 LIMIT 1
```

Sort of related question. Why do recipes belong_to photos vs. the other way around?

**Comment by boblail** [comment]
Whoops! This commit 11fc1cf96e6437f288afcd93ed30a0daa235fd78 should fix that.

**Comment by boblail** [comment]
> Why do recipes belong_to photos vs. the other way around?

In the New Recipe view, when you select an image, the photo gets uploaded, saved, and shown back to you — so the photo exists before the recipe does. I put the foreign key on recipe rather than updating `photo.recipe_id` after the recipe was saved because it was slightly easier.

Although, I could see this changing at some point if recipes are allowed to have multiple photos — or photos within the instructions.
